### ISSUE TITLE
fixed container size support

### ISSUE THREAD

**Issue by mreinstein** [bryanburgers/bin-pack#1]
@bryanburgers  my use case for this module is to intelligently sort inventory items for a role playing game. As such, I have a fixed size container (the character's knapsack) and want to constrain bin packing to these dimensions.  

I'm thinking I'd create some option like `constraints: { width: 256: height: 256 }` in the contructor. 

Would you accept a pull request that adds this feature?

**Comment by bryanburgers** [comment]
Absolutely. And if you want to take over this library, you may do that, too.

**Comment by mreinstein** [comment]
@bryanburgers I've implemented this, but I think it makes sense as it's own module. The API is a bit different, in that constrained binpacking has a failure mode (when things can't fit into the given dimensions. ) So given that, I think this module is good as-is.
